# Generated by Django 4.1.2 on 2022-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('legs', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
