# Generated by Django 4.1.2 on 2022-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.Field(max_length=30)),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
